<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.3 (Python 3.8.10 on linux)" generated="20220629 21:39:58.111" rpa="false" schemaversion="2">
<suite id="s1" name="Test Connection" source="/home/marcelo/robot_framework/robot_hub_eldorado/test_connection.robot">
<test id="s1-t1" name="Connect to devices">
<kw name="use genie testbed &quot;${testbed}&quot;" library="genie.libs.robot.GenieRobot" sourcename="use genie testbed &quot;${testbed}&quot;">
<doc>*DEPRECATED* Please use the "use testbed "${testbed}" keyword instead.</doc>
<msg timestamp="20220629 21:39:59.118" level="WARN">Keyword 'genie.libs.robot.GenieRobot.use genie testbed "${testbed}"' is deprecated. Please use the "use testbed "${testbed}" keyword instead.</msg>
<msg timestamp="20220629 21:39:59.129" level="WARN">Using the default YAML encoding key since no key was specified in configuration.
THIS IS A SHARED KEY AND IS NOT SECURE, PLEASE RUN `pyats secret keygen` AND ADD TO YOUR pyats.conf FILE BEFORE ENCODING ANY VALUES.</msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">+------------------------------------------------------------------------------+
|                            Genie datafiles used:                             |
+------------------------------------------------------------------------------+</msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">Trigger datafile          | </msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">Verification  datafile    | </msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">Pts datafile              | /home/marcelo/robot_framework/env_robot/lib/python3.8/site-packages/genie/libs/sdk/genie_yamls/pts_datafile.yaml</msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">Subsection datafile       | /home/marcelo/robot_framework/env_robot/lib/python3.8/site-packages/genie/libs/sdk/genie_yamls/subsection_datafile.yaml</msg>
<msg timestamp="20220629 21:39:59.175" level="INFO">Config datafile           | None</msg>
<msg timestamp="20220629 21:39:59.199" level="WARN">Could not load the trigger datafile correctly, did you specify 'uut' device alias?</msg>
<status status="PASS" starttime="20220629 21:39:59.118" endtime="20220629 21:39:59.200"/>
</kw>
<kw name="connect to device &quot;HUB_VIA-A23-SW01&quot;" library="ats.robot.pyATSRobot" sourcename="connect to device &quot;${device:[^&quot;]+}&quot;">
<doc>Connect to device connection as defined in testbed.yaml</doc>
<msg timestamp="20220629 21:39:59.201" level="INFO">Connecting to device 'Device HUB_VIA-A23-SW01, type iosxe'</msg>
<msg timestamp="20220629 21:39:59.201" level="INFO">kwargs: {}</msg>
<msg timestamp="20220629 21:40:10.289" level="INFO">2022-06-29 21:39:59,203: %UNICON-INFO: +++ HUB_VIA-A23-SW01 logfile /tmp/HUB_VIA-A23-SW01-cli-20220629T213959202.log +++

2022-06-29 21:39:59,204: %UNICON-INFO: +++ Unicon plugin iosxe (unicon.plugins.iosxe) +++
Unable to negotiate with 10.211.19.10 port 22: no matching key exchange method found. Their offer: diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1


2022-06-29 21:39:59,261: %UNICON-INFO: +++ connection to spawn: ssh -l svc_telecom 10.211.19.10, id: 140507650462432 +++

2022-06-29 21:39:59,262: %UNICON-INFO: connection to HUB_VIA-A23-SW01</msg>
<msg timestamp="20220629 21:40:10.291" level="FAIL">ConnectionError: failed to connect to HUB_VIA-A23-SW01
Failed while bringing device to "any" state</msg>
<status status="FAIL" starttime="20220629 21:39:59.200" endtime="20220629 21:40:10.292"/>
</kw>
<doc>Define the hosts to connect and test connection</doc>
<tag>Hub</tag>
<status status="FAIL" starttime="20220629 21:39:59.117" endtime="20220629 21:40:10.292">ConnectionError: failed to connect to HUB_VIA-A23-SW01
Failed while bringing device to "any" state</status>
</test>
<status status="FAIL" starttime="20220629 21:39:58.115" endtime="20220629 21:40:10.293"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">Hub</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Connection">Test Connection</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20220629 21:39:59.118" level="WARN">Keyword 'genie.libs.robot.GenieRobot.use genie testbed "${testbed}"' is deprecated. Please use the "use testbed "${testbed}" keyword instead.</msg>
<msg timestamp="20220629 21:39:59.129" level="WARN">Using the default YAML encoding key since no key was specified in configuration.
THIS IS A SHARED KEY AND IS NOT SECURE, PLEASE RUN `pyats secret keygen` AND ADD TO YOUR pyats.conf FILE BEFORE ENCODING ANY VALUES.</msg>
<msg timestamp="20220629 21:39:59.199" level="WARN">Could not load the trigger datafile correctly, did you specify 'uut' device alias?</msg>
</errors>
</robot>
