<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.1 (Python 3.10.6 on linux)" generated="20221215 19:25:55.310" rpa="false" schemaversion="3">
<suite id="s1" name="Test Connection" source="/home/marcelo/laboratorio/robotframework/robot_lab/0-test-connection/test_connection.robot">
<test id="s1-t1" name="Connect to devices" line="12">
<kw name="use genie testbed &quot;${testbed}&quot;" library="genie.libs.robot.GenieRobot" sourcename="use genie testbed &quot;${testbed}&quot;">
<doc>*DEPRECATED* Please use the "use testbed "${testbed}" keyword instead.</doc>
<msg timestamp="20221215 19:25:57.826" level="WARN">Keyword 'genie.libs.robot.GenieRobot.use genie testbed "${testbed}"' is deprecated. Please use the "use testbed "${testbed}" keyword instead.</msg>
<msg timestamp="20221215 19:25:57.831" level="WARN">Using the default YAML encoding key since no key was specified in configuration.
THIS IS A SHARED KEY AND IS NOT SECURE, PLEASE RUN `pyats secret keygen` AND ADD TO YOUR pyats.conf FILE BEFORE ENCODING ANY VALUES.</msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">+------------------------------------------------------------------------------+
|                            Genie datafiles used:                             |
+------------------------------------------------------------------------------+</msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">Trigger datafile          | </msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">Verification  datafile    | </msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">Pts datafile              | /home/marcelo/venv_lab/lib/python3.10/site-packages/genie/libs/sdk/genie_yamls/pts_datafile.yaml</msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">Subsection datafile       | /home/marcelo/venv_lab/lib/python3.10/site-packages/genie/libs/sdk/genie_yamls/subsection_datafile.yaml</msg>
<msg timestamp="20221215 19:25:57.916" level="INFO">Config datafile           | None</msg>
<msg timestamp="20221215 19:25:57.930" level="WARN">Could not load the trigger datafile correctly, did you specify 'uut' device alias?</msg>
<status status="PASS" starttime="20221215 19:25:57.826" endtime="20221215 19:25:57.930"/>
</kw>
<kw name="connect to device &quot;NXOS&quot;" library="ats.robot.pyATSRobot" sourcename="connect to device &quot;${device:[^&quot;]+}&quot;">
<doc>Connect to device connection as defined in testbed.yaml</doc>
<msg timestamp="20221215 19:25:57.931" level="INFO">Connecting to device 'Device NXOS, type nxos'</msg>
<msg timestamp="20221215 19:25:57.931" level="INFO">kwargs: {}</msg>
<msg timestamp="20221215 19:26:12.053" level="INFO">2022-12-15 19:25:57,934: %UNICON-INFO: +++ NXOS logfile /tmp/NXOS-cli-20221215T192557933.log +++

2022-12-15 19:25:57,934: %UNICON-INFO: +++ Unicon plugin nxos (unicon.plugins.nxos) +++
ssh: connect to host 192.168.15.212 port 22: No route to host


2022-12-15 19:26:01,028: %UNICON-INFO: +++ connection to spawn: ssh -l admin 192.168.15.212, id: 140265600990944 +++

2022-12-15 19:26:01,028: %UNICON-INFO: connection to NXOS</msg>
<msg timestamp="20221215 19:26:12.053" level="FAIL">ConnectionError: failed to connect to NXOS
Failed while bringing device to "any" state</msg>
<status status="FAIL" starttime="20221215 19:25:57.930" endtime="20221215 19:26:12.058"/>
</kw>
<doc>Define the hosts to connect and test connection</doc>
<tag>Laboratorio</tag>
<status status="FAIL" starttime="20221215 19:25:57.825" endtime="20221215 19:26:12.059">ConnectionError: failed to connect to NXOS
Failed while bringing device to "any" state</status>
</test>
<status status="FAIL" starttime="20221215 19:25:55.310" endtime="20221215 19:26:12.064"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">Laboratorio</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Test Connection">Test Connection</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20221215 19:25:57.826" level="WARN">Keyword 'genie.libs.robot.GenieRobot.use genie testbed "${testbed}"' is deprecated. Please use the "use testbed "${testbed}" keyword instead.</msg>
<msg timestamp="20221215 19:25:57.831" level="WARN">Using the default YAML encoding key since no key was specified in configuration.
THIS IS A SHARED KEY AND IS NOT SECURE, PLEASE RUN `pyats secret keygen` AND ADD TO YOUR pyats.conf FILE BEFORE ENCODING ANY VALUES.</msg>
<msg timestamp="20221215 19:25:57.930" level="WARN">Could not load the trigger datafile correctly, did you specify 'uut' device alias?</msg>
</errors>
</robot>
